### ISSUE TITLE
Error using chef-client 12.2.1

### ISSUE THREAD

**Issue by dblessing** [rtkwlf/cookbook-simple-iptables#68]
The following error occurs in Chef Client 12.2.1:

```
           NoMethodError
           -------------
           Undefined node attribute or method `<<' on `node'. To set an attribute, use `<<=value' instead.
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/simple_iptables/providers/rule.rb:34:in `block in handle_rule'
           /tmp/kitchen/cache/cookbooks/simple_iptables/providers/rule.rb:28:in `each'
           /tmp/kitchen/cache/cookbooks/simple_iptables/providers/rule.rb:28:in `handle_rule'
           /tmp/kitchen/cache/cookbooks/simple_iptables/providers/rule.rb:7:in `block in class_from_file'
```

**Comment by dblessing** [comment]
Nevermind. Forgot to `include_recipe 'simple_iptables'`
