### ISSUE TITLE
NoMethodError: undefined method `lazy'

### ISSUE THREAD

**Issue by fughz** [rtkwlf/cookbook-simple-iptables#72]
I got this error message when I provisioning.
I used ruby 2.2.0 and chef 11.12.4 
```
$ sudo head /var/chef/cache/chef-stacktrace.out
Generated at 2015-06-24 14:13:14 +0000
NoMethodError: undefined method `lazy' for #<Class:0x00000002acebb0>
/tmp/vagrant-chef/24908995bd1fac04ad7e673dc8bbe2b2/cookbooks/simple_iptables/resources/rule.rb:10:in `class_from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.2/lib/chef/mixin/from_file.rb:42:in `class_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.2/lib/chef/mixin/from_file.rb:42:in `class_from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.2/lib/chef/resource/lwrp_base.rb:54:in `build_from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.2/lib/chef/run_context/cookbook_compiler.rb:220:in `load_lwrp_resource'
```

Maybe, This line seems wrong...?
https://github.com/rtkwlf/cookbook-simple-iptables/blob/master/resources/rule.rb
```ruby
attribute :comment, :kind_of => String, :default => lazy { |r| r.name }
```

**Comment by fughz** [comment]
I used this rule.
```ruby
# Cookbook Name:: rails_book_cookbook
# Recipe:: iptables
include_recipe "simple_iptables"

# Default Policy
simple_iptables_policy "INPUT" do
  policy "DROP"
end

# enable loopback
simple_iptables_rule "local" do
  rule "--in-interface lo"
  jump "ACCEPT"
end

# enable already connected
simple_iptables_rule "established" do
  rule "-m conntrack --ctstate ESTABLISHED,RELATED"
  jump "ACCEPT"
end

# enable ssh
simple_iptables_rule "ssh" do
  rule "--proto tcp --dport 22"
  jump "ACCEPT"
end

# enable HTTP, HTTPS
simple_iptables_rule "http" do
  rule [ "--proto tcp --dport 80",
         "--proto tcp --dport 443 ]
  jump "ACCEPT"
end
```

**Comment by rtkrruvinskiy** [comment]
@fughz Thanks for reporting this! Can you try the patch in https://github.com/rtkwlf/cookbook-simple-iptables/pull/73? If it works for you, I'll merge and cut a new release.

**Comment by fughz** [comment]
Thanks! my provisioning was succeded.
