### ISSUE TITLE
Issue with chef 12.11.18 and simple_iptables

### ISSUE THREAD

**Issue by jasondcamp** [rtkwlf/cookbook-simple-iptables#80]
I downloaded 0.7.4 of simple_iptables, and tried to implement the first example rule:

```
# Allow SSH
simple_iptables_rule "ssh" do
  rule "--proto tcp --dport 22"
  jump "ACCEPT"
end
```

And I'm getting this during a chef run:
```
  * simple_iptables_rule[ssh] action append

    ================================================================================
    Error executing action `append` on resource 'simple_iptables_rule[ssh]'
    ================================================================================

    NoMethodError
    -------------
    Undefined node attribute or method `<<' on `node'. To set an attribute, use `<<=value' instead.

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/simple_iptables/providers/rule.rb:27:in `handle_rule'
    /var/chef/cache/cookbooks/simple_iptables/providers/rule.rb:8:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/jump_server/recipes/default.rb

     26: simple_iptables_rule "ssh" do
     27:   rule "--proto tcp --dport 22"
     28:   jump "ACCEPT"
     29: end
     30:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/jump_server/recipes/default.rb:26:in `from_file'

    simple_iptables_rule("ssh") do
      action :append
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :simple_iptables_rule
      cookbook_name "jump_server"
      recipe_name "default"
      rule "--proto tcp --dport 22"
      jump "ACCEPT"
      table "filter"
      chain "ssh"
      direction "INPUT"
    end

    Platform:
    ---------
    x86_64-linux


Running handlers:
[2016-06-26T21:25:21+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-06-26T21:25:21+00:00] ERROR: Exception handlers complete
Chef Client failed. 2 resources updated in 10 seconds
[2016-06-26T21:25:21+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-06-26T21:25:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-06-26T21:25:21+00:00] ERROR: simple_iptables_rule[ssh] (jump_server::default line 26) had an error: NoMethodError: Undefined node attribute or method `<<' on `node'. To set an attribute, use `<<=value' instead.
[2016-06-26T21:25:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Let me know if there's anything else I can provide to help, thanks!

**Comment by jasondcamp** [comment]
Whoops, saw a PR and existing ticket here for the issue, closing.
